"""empty message

Revision ID: 2d745e7111e3
Revises: 
Create Date: 2025-06-30 09:25:26.665037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d745e7111e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('file')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file', sa.VARCHAR(length=200), nullable=False))
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
