"""initial migration

Revision ID: acba55676f3a
Revises: 40ebbc6d3807
Create Date: 2025-06-30 11:21:03.986287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acba55676f3a'
down_revision = '40ebbc6d3807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_email', ['email'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_email', ['email'])
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('file')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file', sa.VARCHAR(length=200), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint('uq_user_email', type_='unique')

    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_email', type_='unique')

    # ### end Alembic commands ###
